// <auto-generated />
using System;
using JuhMesquitaViagens.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JuhMesquitaViagens.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("JuhMesquitaViagens.Models.Destiny", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("municipality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("promotion")
                        .HasColumnType("bit");

                    b.Property<string>("state")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("valueDaily")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.ToTable("Destiny");
                });

            modelBuilder.Entity("JuhMesquitaViagens.Models.Package", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<int>("adults")
                        .HasColumnType("int");

                    b.Property<DateTime>("dateGoing")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dateReturn")
                        .HasColumnType("datetime2");

                    b.Property<int>("destinyid")
                        .HasColumnType("int");

                    b.Property<int>("kids")
                        .HasColumnType("int");

                    b.Property<string>("origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("payment")
                        .HasColumnType("float");

                    b.Property<int>("userid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("destinyid");

                    b.HasIndex("userid");

                    b.ToTable("Package");
                });

            modelBuilder.Entity("JuhMesquitaViagens.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<bool>("administrator")
                        .HasColumnType("bit");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("JuhMesquitaViagens.Models.Package", b =>
                {
                    b.HasOne("JuhMesquitaViagens.Models.Destiny", "destiny")
                        .WithMany()
                        .HasForeignKey("destinyid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JuhMesquitaViagens.Models.User", "user")
                        .WithMany("package")
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("destiny");

                    b.Navigation("user");
                });

            modelBuilder.Entity("JuhMesquitaViagens.Models.User", b =>
                {
                    b.Navigation("package");
                });
#pragma warning restore 612, 618
        }
    }
}
